### PR TITLE
Disable currency input frequency selects when input is 0

### PR DESCRIPTION
**Pull request by tyom**
screen shot 2015-07-07 at 14 09 41

### CODE REVIEW

**Comment by tyom** [comment]
test this please

**Comment by pidah** [comment]
retest this please

**Comment by tyom** [comment]
test this please

**Comment by tyom** [comment]
test this please

**Comment by milror00** [comment]
retest this please

**Comment by milror00** [comment]
retest this please

**Comment by milror00** [comment]
retest this please

**Comment by milror00** [comment]
retest this please

**Comment by s-block** [comment]
Can one of the admins verify this patch?

**Comment by sldblog** [comment]
@ministryofjustice/laa-get-access is this change still needed?

**Comment by sldblog** [comment]
Closing due to inactivity.

**Pull request closed without merging**
