### PR TITLE
LGA-3027 - Add hlpas page after user fails means

### PR DESCRIPTION
**Pull request by said-moj**
## What does this pull request do?

Add hlpas page after user fails means

## Any other changes that would benefit highlighting?

Separate PR to fix failing end-to-end tests due to hlpas changes https://github.com/ministryofjustice/cla-end-to-end-tests/pull/137

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by TawneeOwl — DISMISSED** [review]
LGTM

**Comment by BenMillar-CGI** [comment]
Thanks for this Said, great stuff!

Would it be possible for the fixes made in [this commit](https://github.com/ministryofjustice/cla_public/pull/1254/files) to be reflected in this PR please?

Many thanks and please let me know if you have any questions.

**Review by TawneeOwl — DISMISSED** [review]
LGTM

**Review by BenMillar-CGI — DISMISSED** [review]

**Review by BenMillar-CGI — APPROVED** [review]
LGTM, great stuff! 👍

**Review by TawneeOwl — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
