### PR TITLE
Feature/scope

### PR DESCRIPTION
**Pull request by s-block**

### CODE REVIEW

**Comment by s-block** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by andyhd** [comment]
retest this please

**Comment by s-block** [comment]
retest this please

**Comment by axemonkey** [comment]
retest this please

**Comment by s-block** [comment]
retest this please

**Comment by s-block** [comment]
retest this please

**Comment by s-block** [comment]
retest this please

**Comment by axemonkey** [comment]
I think the tests should pass once backend PR 330 is merged.

**Comment by axemonkey** [comment]
retest this please

**Comment by axemonkey** [comment]
retest this please

**Comment by axemonkey** [comment]
retest this please

**Comment by tyom** [comment]
test this please

**Comment by tyom** [comment]
test this please

**Comment by tyom** [comment]
test this please

**Comment by axemonkey** [comment]
retest this please

**Comment by axemonkey** [comment]
retest this please

**Pull request merged**
