### PR TITLE
Replace AddressFinder with PostcodeInfo

### PR DESCRIPTION
**Pull request by andyhd**

### CODE REVIEW

**Comment by andyhd** [comment]
Test failing because there's no token for CLA

**Comment by andyhd** [comment]
@jenkins-moj retest this please

**Comment by s-block** [comment]
Can one of the admins verify this patch?

**Comment by s-block** [comment]
retest this please

**Comment by s-block** [comment]
test this please

**Comment by s-block** [comment]
test this please

**Comment by s-block** [comment]
retest this please

**Comment by s-block** [comment]
test this please

**Comment by s-block** [comment]
test this please

**Comment by s-block** [comment]
test this please

**Comment by andyhd** [comment]
test this please

**Comment by s-block** [comment]
test this please

**Comment by s-block** [comment]
test this please

**Comment by s-block** [comment]
test this please

**Pull request merged**
