### PR TITLE
LGA-1407 numbers

### PR DESCRIPTION
**Pull request by MalcolmVonMoJ**
## What does this pull request do?

Adds a `pattern` and `inputmode=numeric` to the integer entry fields for _**number of depentants**_ and _**number of children**_.  
Removes the same from the currency fields as per GDS guidelines.  

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by mayowaadeniyi — COMMENTED** [review]
Error messages won't be uniform with these changes, but I am assuming as you said in your last commit, these are the recommended changes by GDS?

image

**Comment by MalcolmVonMoJ** [comment]
Yes, that's right.  The inclusion of the `pattern` element which brings up these HTML errors help get the correct keyboard for mobile devices.  I shall look into this again to be sure.

**Comment by MalcolmVonMoJ** [comment]
I've added a `novalidate` at the top, which should have been there anyway. So that issue is now solved.

**Review by mayowaadeniyi — COMMENTED** [review]
Very minor but could we change the * to a + on the controlled_by=form `pattern` attribute so it has to be a number? Or we could remove it entirely since it won't be validated anyway 😅

**Comment by MalcolmVonMoJ** [comment]
I don't know - so no.  I think we should keep it as the GDS pattern.  They say:

> it's used to trigger the numeric keypad on iOS < 12.2

We could test to see whether + or something else has the same effect, but I don't see the point.

**Review by mayowaadeniyi — APPROVED** [review]
LGTM 👍

**Pull request merged**
