### PR TITLE
remove BETA tag

### PR DESCRIPTION
**Pull request by ushkarev**
service has passed live assessment

### CODE REVIEW

**Comment by ushkarev** [comment]
might want to re-word: “This is a new service – your feedback will help us to improve it.”

**Comment by tyom** [comment]
:+1:

**Comment by tomdolanmoj** [comment]
HUSSAH!

**Comment by zzgavin** [comment]
brilliant news, well done

**Comment by teneightfive** [comment]
image

**Comment by kerin** [comment]
Excellent gif work everyone.

**Pull request merged**
