### PR TITLE
copy for mental health f2f page

### PR DESCRIPTION
**Pull request by axemonkey**
[Pivotal](https://www.pivotaltracker.com/story/show/94508888)

### CODE REVIEW

**Comment by tyom** [comment]
:+1:

**Comment by axemonkey** [comment]
retest this please

**Comment by axemonkey** [comment]
retest this please

**Comment by axemonkey** [comment]
retest this please

**Comment by axemonkey** [comment]
retest this please

**Comment by pidah** [comment]
retest this please

**Comment by pidah** [comment]
retest this please

**Pull request merged**
