### PR TITLE
LGA 2788 Remove old Notify client code

### PR DESCRIPTION
**Pull request by BenMillar-CGI**
### [LGA 2788](https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/boards/226?selectedIssue=LGA-2788)

- Removes references to the old GovUkNotify class
- Removes the feature flag that was implemented to switch between these classes
- Removes the now unneeded unit test for that feature flag
- Removes references to the now unneeded environment variables

## Any other changes that would benefit highlighting?

- Adds .vscode to .gitignore to stop my IDE from trying to commit config files

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by TawneeOwl — APPROVED** [review]
LGTM

**Review by psweeting1 — APPROVED** [review]
LGTM

**Review by Pheonnexx — APPROVED** [review]
LGTM :shipit:

**Review by said-moj — APPROVED** [review]
👍 LGTM

**Pull request merged**
