### PR TITLE
BSL legal aid available content changes

### PR DESCRIPTION
**Pull request by said-moj**
## What does this pull request do?

BSL legal aid available content changes.

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by digitalali-moj — DISMISSED** [review]
Thanks LGTM - probably best to test content on test env as it's a lot of  content.

**Review by Pheonnexx — DISMISSED** [review]
LGTM

**Review by digitalali-moj — APPROVED** [review]
Still looks good :)

**Review by Pheonnexx — APPROVED** [review]

**Review by BenMillar-MOJ — APPROVED** [review]
LGTM, thank you very much! 👍

**Pull request merged**
