### PR TITLE
don't run threshold tests locally any more

### PR DESCRIPTION
**Pull request by axemonkey**

### CODE REVIEW

**Comment by axemonkey** [comment]
retest this please

**Comment by andyhd** [comment]
:+1:

**Comment by tyom** [comment]
Should we remove `threshold.js` if we're not using it any more?

**Comment by axemonkey** [comment]
Josh seemed keen on keeping it in case we wanted it again in the future. I'm fine with losing it as well as all the threshold json files, as they'll be in the github history.

**Comment by tyom** [comment]
> as they'll be in the github history.

That's what I thought.

**Comment by s-block** [comment]
I have still been running them as the unit tests have changed a lot

**Comment by axemonkey** [comment]
Sooo...?

**Comment by tyom** [comment]
@s-block Do you still use them?

**Comment by tyom** [comment]
Discussed off-line. The consensus seems to be to move Threshold test to a different directory ([group](http://nightwatchjs.org/guide#runner-options)) and exclude by default. Perhaps adding a command to run all tests.

**Pull request closed without merging**
