### PR TITLE
Review URLs

### PR DESCRIPTION
**Pull request by tyom**

### CODE REVIEW

**Comment by tyom** [comment]
test this please

**Comment by ushkarev** [comment]
the context debugger still refers to an old url, maybe consider:
```diff
diff --git a/cla_public/templates/_context-debugger.html b/cla_public/templates/_context-debugger.html
index 8661982..e6ea73a 100644
--- a/cla_public/templates/_context-debugger.html
+++ b/cla_public/templates/_context-debugger.html
@@ -114,7 +114,7 @@
     {% if session.checker.category_slug %}
       <li class="_separator"></li>
       <li>
-        <a href="/help-organisations/{{session.checker.category_slug}}">Ineligible</a>
+        <a href="{{ url_for('checker.help_organisations', category_name=session.checker.category_slug) }}">Ineligible</a>
       </li>
     {% endif %}
   </menu>
```

**Comment by tyom** [comment]
> the context debugger still refers to an old url

Well spotted. Updated.

**Comment by tyom** [comment]
test this please

**Comment by tyom** [comment]
test this please

**Comment by tyom** [comment]
test this please

**Comment by s-block** [comment]
:+1:

**Pull request merged**
