### PR TITLE
Fix breaking tests

### PR DESCRIPTION
**Pull request by axemonkey**

### CODE REVIEW

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by axemonkey** [comment]
@jenkins-moj retest this please

**Comment by s-block** [comment]
looks good

**Pull request merged**
