### PR TITLE
FE: Add print button on Confirmation page

### PR DESCRIPTION
**Pull request by tyom**

### CODE REVIEW

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
rebuild this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by axemonkey** [comment]
Nice. Looks good.

**Pull request merged**
