### PR TITLE
Feature/LGA 387 accessibility statement

### PR DESCRIPTION
**Pull request by joshlow**
## What does this pull request do?

Publishes an accessibility statement page, linked from the footer of the service

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

Related ticket:
https://dsdmoj.atlassian.net/browse/LGA-387

### CODE REVIEW

**Review by exonian — COMMENTED** [review]
Flask stuff looks good to me. I've glanced at the template and nothing jumps out but I'll leave the sign-off to @mayowaadeniyi

**Review by mayowaadeniyi — COMMENTED** [review]
This looks good to me. I see we haven't got the Welsh in place for this yet. Is it still okay to go forward without it?

**Comment by joshlow** [comment]
Hi @mayowaadeniyi - yes, we can publish the English content and then I'll send it off for translation. It means bi-lingual content isn't published simultaneously but will follow shortly after, usually 2-3 weeks.

**Review by mayowaadeniyi — APPROVED** [review]
LGTM 👍

**Pull request merged**
