### PR TITLE
Google Analytics

### PR DESCRIPTION
**Pull request by tyom**
* [x] Add ability to send events and page views inline from anchor tags (via `data-ga` attribute)
* [x] Send event when locale is changed
* [x] Send event when preferred callback time is changed

### CODE REVIEW

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by tyom** [comment]
retest this please

**Comment by s-block** [comment]
Looks good, Can you squash this in to one commit so it is easier to cherry pick in to a hotfix?

**Comment by axemonkey** [comment]
LGTM

**Pull request merged**
